services:
  web:
    build: .
    ports:
      - "8080:80"
      - "2222:22"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./prestashop-1.5.6.2:/var/www/html
      - prestashop_data:/var/www/html/modules/blocklayered/cache
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cubecart
    volumes:
       - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  prestashop_data:
  db_data:
