services:
  web:
    image: dirkmei/ctf-repo:web2
    entrypoint: ["/usr/local/bin/start.sh"]
    ports:
      - "8080:80"
      - "2222:22"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./prestashop-1.5.6.2:/var/www/html
      - prestashop_data:/var/www/html/modules/blocklayered/cache
    depends_on:
      - db

  db:
    image: dirkmei/ctf-repo:db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cubecart
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql

volumes:
  prestashop_data:
  db_data: